apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: rhtap-demo-component-rpcv
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: var_name
          value: test
        image: quay.io/ysubrama_org/rhtap-demo-dev-reml-tenant/mvp-test-app/rhtap-demo-component-rpcv@sha256:c43ac15b06b04659e1ecf021fed09443e0d0ec0316b2cf2c3d6bc77953b05342
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
