apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rhtap-demo-component-rpcv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhtap-demo-component-rpcv
    app.kubernetes.io/part-of: mvp-test-app
  name: rhtap-demo-component-rpcv
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: rhtap-demo-component-rpcv
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: rhtap-demo-component-rpcv
    spec:
      containers:
      - image: quay.io/ysubrama_org/rhtap-demo-dev-reml-tenant/mvp-test-app/rhtap-demo-component-rpcv@sha256:c43ac15b06b04659e1ecf021fed09443e0d0ec0316b2cf2c3d6bc77953b05342
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
